# Generated by Django 3.2 on 2023-05-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(default='static/images/no_image.png', upload_to='static/images/company/'),
        ),
    ]
