# Generated by Django 3.2 on 2023-05-29 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.category')),
            ],
        ),
    ]
