# Generated by Django 3.2 on 2023-05-29 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.subcategory'),
            preserve_default=False,
        ),
    ]
